### ISSUE TITLE
Update gem to newer version

### ISSUE THREAD

**Issue by reepush** [se3000/angular-ui-select-rails#1]
Now ui-select is of version 0.12.0 and this gem is 0.9.5.
Are you interested in keeping this gem up to date? Also I am going to open an issue in angular-ui organization about gems publishing, maybe it could be done in one place.

**Comment by se3000** [comment]
Yeah, I'd like to keep it updated I just don't follow that closely.

I'll upgrade/test it in the next few days and push out the gem shortly after.

**Comment by se3000** [comment]
Ok, updated. Feel free to reopen if there's something wrong, or ping me when it gets out of date again. Pull requests are also welcome.
