### ISSUE TITLE
select2-rails dependency

### ISSUE THREAD

**Issue by hanchennz** [se3000/angular-ui-select-rails#2]
Hey Steve, maybe it's overkill but I didn't notice this during my fresh install. I just followed the instructions in the read me and didn't realize that I needed select2-rails as well. Maybe this is helpful to put? 

require "jquery-rails"
require "select2-rails"

**Comment by se3000** [comment]
Good point. I'll remove those from the repo and update the instructions for including the different style options.

**Comment by se3000** [comment]
@hanchennz just fixed this issue, and updated to the newest version of ui-select. Released a new gem version, 0.12.1, where this should be fixed.

Please update and let me know if you run into other issues.
